/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const schools_Logic = require('./code/schools-logic');

class student_Details_JouleSrv extends LCAPApplicationService {
    async init() {

        this.before(['CREATE', 'UPDATE'], 'Schools', async (request) => {
            await schools_Logic(request);
        });

        return super.init();
    }
}


module.exports = {
    student_Details_JouleSrv
};